package com.rapstar.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFollowing<M extends BaseFollowing<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setStar(java.lang.Integer star) {
		set("star", star);
		return (M)this;
	}
	
	public java.lang.Integer getStar() {
		return getInt("star");
	}

	public M setFollower(java.lang.Integer follower) {
		set("follower", follower);
		return (M)this;
	}
	
	public java.lang.Integer getFollower() {
		return getInt("follower");
	}

}
