package com.rapstar.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSong<M extends BaseSong<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAuthorid(java.lang.Integer authorid) {
		set("authorid", authorid);
		return (M)this;
	}
	
	public java.lang.Integer getAuthorid() {
		return getInt("authorid");
	}

	public M setLyricpath(java.lang.String lyricpath) {
		set("lyricpath", lyricpath);
		return (M)this;
	}
	
	public java.lang.String getLyricpath() {
		return getStr("lyricpath");
	}

	public M setAcc(java.lang.Integer acc) {
		set("acc", acc);
		return (M)this;
	}
	
	public java.lang.Integer getAcc() {
		return getInt("acc");
	}

	public M setStyle(java.lang.Integer style) {
		set("style", style);
		return (M)this;
	}
	
	public java.lang.Integer getStyle() {
		return getInt("style");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setMoney(java.lang.Double money) {
		set("money", money);
		return (M)this;
	}
	
	public java.lang.Double getMoney() {
		return getDouble("money");
	}

	public M setImgpath(java.lang.String imgpath) {
		set("imgpath", imgpath);
		return (M)this;
	}
	
	public java.lang.String getImgpath() {
		return getStr("imgpath");
	}

}
