package com.rapstar.model;

import com.rapstar.model.base.BaseAcccollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Acccollect extends BaseAcccollect<Acccollect> {
	public static final Acccollect dao = new Acccollect().dao();
}
