package com.rapstar.model;

import com.rapstar.model.base.BaseAcclist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Acclist extends BaseAcclist<Acclist> {
	public static final Acclist dao = new Acclist().dao();
}
