package com.rapstar.model;

import com.rapstar.model.base.BaseAccompaniment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Accompaniment extends BaseAccompaniment<Accompaniment> {
	public static final Accompaniment dao = new Accompaniment().dao();
}
