package com.rapstar.model;

import com.rapstar.model.base.BaseAlistdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Alistdetail extends BaseAlistdetail<Alistdetail> {
	public static final Alistdetail dao = new Alistdetail().dao();
}
