package com.rapstar.model;

import com.rapstar.model.base.BaseDemocollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Democollect extends BaseDemocollect<Democollect> {
	public static final Democollect dao = new Democollect().dao();
}
