package com.rapstar.model;

import com.rapstar.model.base.BaseDemolist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Demolist extends BaseDemolist<Demolist> {
	public static final Demolist dao = new Demolist().dao();
}
