package com.rapstar.model;

import com.rapstar.model.base.BaseDlistdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dlistdetail extends BaseDlistdetail<Dlistdetail> {
	public static final Dlistdetail dao = new Dlistdetail().dao();
}
