package com.rapstar.model;

import com.rapstar.model.base.BaseFollowing;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Following extends BaseFollowing<Following> {
	public static final Following dao = new Following().dao();
}
