package com.rapstar.model;

import com.rapstar.model.base.BaseMusician;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Musician extends BaseMusician<Musician> {
	public static final Musician dao = new Musician().dao();
}
