package com.rapstar.model;

import com.rapstar.model.base.BaseSlistcollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Slistcollect extends BaseSlistcollect<Slistcollect> {
	public static final Slistcollect dao = new Slistcollect().dao();
}
