package com.rapstar.model;

import com.rapstar.model.base.BaseSlistdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Slistdetail extends BaseSlistdetail<Slistdetail> {
	public static final Slistdetail dao = new Slistdetail().dao();
}
