package com.rapstar.model;

import com.rapstar.model.base.BaseSongcollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Songcollect extends BaseSongcollect<Songcollect> {
	public static final Songcollect dao = new Songcollect().dao();
}
