package com.rapstar.model;

import com.rapstar.model.base.BaseSong;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Song extends BaseSong<Song> {
	public static final Song dao = new Song().dao();
}
