package com.rapstar.model;

import com.rapstar.model.base.BaseSonglist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Songlist extends BaseSonglist<Songlist> {
	public static final Songlist dao = new Songlist().dao();
}
