package com.rapstar.model;

import com.rapstar.model.base.BaseStyle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Style extends BaseStyle<Style> {
	public static final Style dao = new Style().dao();
}
